name: build and publish mpi multi-arch docker image

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      image-name: adysh97/reusable-workflow-docker-image
    secrets: inherit
